### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by ghost** [schae234/studyGroup#14]
Hi, are you still actively pursuing study groups? Do you have an online one that uses something like etherpad?

Regards,
Steve

**Comment by schae234** [comment]
Hey @KipOmaha 

We usually try to meet in person, usually in Hackey Hour format. We've played around with the idea of a more distributed format. Why do you ask?

Rob

**Comment by ghost** [comment]
I was browsing the Moz Sci site and found Omaha, NE doesn`t have anything
and just wanted to see if i could take part online with another group.

Regards Steve
