### ISSUE TITLE
First Study Group Meeting 5pm, July 30

### ISSUE THREAD

**Issue by schae234** [schae234/studyGroup#2]
Meeting will focus on future meetings, a meta meeting of sorts. Tentative topics:
- Goals of future Hackey Hours
- How we can help each other out on side projects and the like
- Making this more accessible to others on the Minnesota Campus

**Comment by schae234** [comment]
### Programming in academia
- How to have a presence in a University setting?
- Remove the focus on science and put it on technology and methods (programming)
- How to not be another XXX_UsersGroup?
- "You are alone together" in terms of programming.

### How we can benefit?
- Zero preparation presentations
- "show your work" coding, and then looking at other peoples code
- Rarely do you get feedback on your code/work
- Learn from looking at other peoples stuff.

### How to "Evangalize"?
- To work well, we need more people
- People need to benefit somehow
- Reach out to other "Hecky Hour" groups?
- Make sharing code less scary

### Next Time
- Overview of another peoples projects/Feedback mechanism
- General technology discussion. socially focused.
- Bigger projects? 
- Should be in a ~~bar~~ restaurant. Thanks joe.

**Comment by kunau** [comment]
Rob,

Sorry to miss the first meeting but I'm out of town.

Glad to be in the loop.

Thank you!,

Tim

On Thursday, July 30, 2015, Rob Schaefer notifications@github.com wrote:

> Programming in academia
> - How to have a presence in a University setting?
> - Remove the focus on science and put it on technology and methods
>   (programming)
> - How to not be another XXX_UsersGroup?
> - "You are alone together" in terms of programming.
> 
> How we can benefit?
> - Zero preparation presentations
> - "show your work" coding, and then looking at other peoples code
> - Rarely do you get feedback on your code/work
> - Learn from looking at other peoples stuff.
> 
> How to "Evangalize"?
> - To work well, we need more people
> - People need to benefit somehow
> - Reach out to other "Hecky Hour" groups?
> - Make sharing code less scary
> 
> Next Time
> - Overview of another peoples projects/Feedback mechanism
> - General technology discussion. socially focused.
> - Bigger projects?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/schae234/studyGroup/issues/2#issuecomment-126515384.

## 

Thanks,

## Timothy

tkunau@gmail.com

**Comment by schae234** [comment]
No problem Tim,
There will definitely be more!
Looking forward to hearing what you are up to lately.
