### ISSUE TITLE
8/27 Hackey Hour

### ISSUE THREAD

**Issue by schae234** [schae234/studyGroup#6]
Last time we met, we decided that if we had things to talk about, why not try to make this _happen more frequently than not_. 

Last time we all tried out a code review type approach on understanding @monprins genewordsearch package. We even submitted multiple pull requests with either suggestions or bug fixes!

**edit: Due to the BICB Industry Sympoisum last week, the 8/20 hackey hour was postponed.**
**Next hackey hour (8/27)** will be focused on a web based tools designed by Justin, in the Myers lab. I think he is working on getting the code up on github, so a link to the repo will follow.

Happy Hacking!
Rob

**Comment by schae234** [comment]
FYI, the next hackey hour is 8/27!

**Comment by bhillmann** [comment]
How do we subscribe to email alerts for the group? Do we star this repository?

**Comment by schae234** [comment]
I think it you just hit the eyeball and watch to Repo, you should get email when people comment and such.

**Comment by bhillmann** [comment]
Perfect, that appears to have done the trick.
