### ISSUE TITLE
9/3 Meeting: Hacking Kaggle

### ISSUE THREAD

**Issue by schae234** [schae234/studyGroup#8]
Ben will be talking about some code he wrote for an online competition using machine learning for classification.

**Comment by bhillmann** [comment]
Is the competition:

https://www.kaggle.com/c/seizure-prediction

And the link to my repository:

https://github.com/bhillmann/gingivere

And I actually have a poster for my submission:

https://drive.google.com/file/d/0B1DZkCeUYapUZ1c4c09hV0VmTmM/view?usp=sharing
